### ISSUE TITLE
Add Augur Hackathons to Site

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/website#506]
@klumb The registration for the Augur site is now live, so you can add it to the website under Meetups. We plan on making this a bi-weekly event as a trial so I don't know how you want to structure that. There will also be Hackathons for our Asia-Pacific group that will happen on Friday evenings on alternate weeks, which also might be a factor to take into consideration.

Here is the link for the Feb 13 2021 Hackathon: https://ti.to/augur/augur-hackathon

Let me know if you have any questions about anything! 

cc @sgoggins

**Comment by klumb** [comment]
Okay,

If these are recurring, we may want to add them to the participate page rather than the meetups navigation. 

Sounds like two new modules on the participate page.

For now I will add the link to the home page.



Cheers, 


Kevin Lumbard, M.S. PMP (he/him/his)
University of Nebraska at Omaha
College of Information Science and Technology
PKI 367

"We build our computers the way we build our cities -- over time, without a plan, on top of ruins" - Ellen Ullman

**Comment by ElizabethN** [comment]
Thanks much @klumb! I really like the idea of adding them to the participate page once we are sure that our regular cadence is something that's useful to the community. We will let you know.

**Comment by seun-beta** [comment]
Hello @ElizabethN & @klumb. About the Augur Hackathon. I can't seem to find it on the community website.
I don't know if it is there. But if there are any plans of adding it should it not formally exist, I would be happy to assist with that. 

Thank you.

**Comment by klumb** [comment]
We don't have any hackathons scheduled currently.

Augur does have some workshops. You can find these under the event's navigation.

I am closing this comment
