### ISSUE TITLE
Update External Links to open on new tabs

### ISSUE THREAD

**Issue by SteveKola** [chaoss/website#533]
Can we enable the external links to open up on new tabs, for a better user experience?

And also, is it something I could possibly work on?

cc: @germonprez

**Comment by germonprez** [comment]
Thanks @SteveKola. I'd love to get the thoughts of @klumb on this.

**Comment by klumb** [comment]
Hi, @SteveKola thank you for your comment and for taking interest in the website and documentation. 

I agree that opening a link in a new tab is the best practice for web design. I was always taught to make the website as sticky as possible - meaning try to keep the visitor on the site and don't give them a reason to leave. 

When we built the website and much of the documentation, we sacrificed this idea in favor of making the documentation and website content as easy as possible for non-coders to edit. Because of this, the website and documentation are all written in GitHub Markdown. To my knowledge, GitHub markdown does not give us the ability to specify that a link opens in a new window. 

There are some workarounds that we have contemplated and I would be interested in hearing your ideas but our current thought is that all CHAOSS content and documentation should be as easy as possible for anyone to edit. We do have the ability to mix some HTML into the markdown files however this would require contributors to use HTML links instead of MarkDown links. I am not sure if that would go over and may cause consistency issues.

There are a few places in the website that are written using HTML and CSS. We created these files when we needed to perform actions or display content and Markdown just wouldn't work. One example of this is the metrics release tables. The links in these tables are HTML links so we could edit them to open in a new window. When we created these links in the tables, we had a discussion about opening them in a new tab but ultimately chose not to - to match the styling of the rest of the website. I am not 100% sure that was the right decision so I would welcome a continued discussion. This is the page and the files I am referring to:

https://chaoss.community/metrics/
https://github.com/chaoss/website/tree/master/release/metrics-tables

**Comment by SteveKola** [comment]
Thank you for the detailed response, @klumb.

I'm totally in sync with the idea of making the docs and website content easy for non-coders to edit. And yes, you're right that having to mix in HTML links might look a bit messy and inconsistent.

So I went searching for answers and I found a solution that involves adding kramdown to the `_config.yml` and using the following syntax; `[link](url){:target="_blank" rel="noopener noreferrer"}`.

I don't know how feasible it is, though. Here is the link to the solution below. You can check it out and see if it is feasible or if the external links are better off the way they are currently.

[https://stackoverflow.com/a/63546509](https://stackoverflow.com/a/63546509)

**Comment by klumb** [comment]
@SteveKola 
There are different types (or flavors of MarkDown). What type of MarkDown is that? GitHub markdown may support that syntax but I haven't seen it in GitHub MarkDown documentation. We could test it. 

If it works we could discuss using it for internal links but I think David Wheeler's point about external links is very valid. So we would need to discuss this further and decide if we want our links to have different behaviors across the site.

**Comment by klumb** [comment]
@SteveKola if you want to test this, put in a PR for this file:

https://github.com/chaoss/website/blob/master/release/download-release-pdf.md 

and we will test it on the website.

**Comment by klumb** [comment]
tests confirm that GitHub markdown doesn't support this solution.

If we decide to implement this change in the future we will need to find another solution.

Closing this issue but we can revisit the idea after the website migration.
