### ISSUE TITLE
Micro-tasks and Overview: Automate Metrics Release and Process Improvement

### ISSUE THREAD

**Issue by klumb** [chaoss/website#537]
CHAOSS metrics are released twice a year. The metrics are currently displayed on the website - sorted by the working group that captured and defined them: https://chaoss.community/metrics/

The official CHAOSS Metrics Release is captured in pdf form at the time of the release by printing each metric page as a PDF and combining them manually. The workflow is described in our handbook. The website pulls in the metrics from Markdown files in the working group GitHub repositories. It would be great if the PDF could be automatically generated from the Markdown files without having to manually PDF print the website pages.

**The aims of the project are as follows:**
- Analyze the metrics release process and propose process improvements.
- Automate the creation of the metrics release PDF from Github Markdown files (Separate PDFs for English and translations).

The aims will require working in a programming language to automate the task. We are open to suggestions about how to achieve this because we do not have any pre-existing automation in place.

Difficulty: Medium  
Requirements: GitHub, git, Markdown, PDF, automation experience  
Recommended: Prior experience with automatic PDF document generation  
Mentors: Kevin Lumbard (@klumb), Matt Germonprez (@germonprez), Georg Link (@GeorgLink) 

**Microtasks:**
1. Attend the weekly community meeting and monthly web content meeting - introduce yourself (if you are shy you can use the chat). Attend each of these meetings at least once. See details for these meetings below.
https://chaoss.community/participate/   

2. Familiar yourself with the website and GitHub repository. Make a pull request (PR) to the website repository - https://github.com/chaoss/website. If you have specific questions about a change you are proposing open an issue. 
- This PR can be any change that makes an improvement to the CHAOSS website - https://chaoss.community/. For example, fixing typos, adding new content, or making certain that content displayed on the website is mapped directly to a markdown file in the repository.  
- Alternately you can submit a PR to the CHAOSS repository that helps document the contribution process and website structure. The process and structure can be difficult to understand for newcomers because the website is hosted on WordPress and website content is primarily created in GitHub markdown and is displayed on the website through an application that pulls directly from the repository (keep this in mind while familiarizing yourself with the website).

3. Create a repository that contains: 
- Two (2) markdown files (you can start with files CHAOSS created and modify them as needed). 
- A single PDF generated from those markdown files. 
- A description of how you generated the PDF from the markdown files. 

4. Provide a link to your repository with evidence that you completed the microtasks when you add your proposal to our GitHub repo: https://github.com/chaoss/governance/blob/master/GSoC-interest.md

**Comment by deepakdinesh1123** [comment]
Should the PDF generator support the complete syntax of markdown or is it enough to just make it convert the metrics markdown to PDF.

For example:
1.Item 1
1.Item 2
    1.Item 3
since these kind of cases are rare is it necessary to add support for it?

**Comment by seun-beta** [comment]
Hello Everyone, 

I am Seunfunmi Adegoke and I'm a senior at the University of Ibadan.
I am a Django developer and I enjoy scripting using Python and building chatbots. I have worked on multiple Python and Django projects and I am also currently a developer community ambassador in my school.

I am interested in this project and I have started work in earnest as regards the Micro-tasks.

An idea just popped in my mind about making contribution easier for beginners. Is there any way beginners that fork the website repo can deploy their markdown and view all the various changes in a sandbox so they can see how their changes would look like on CHAOSS Project's website?

This would also make PR approvals improve because contributors can see how their changes would look like on the website before submitting PR's.
@klumb @GeorgLink @GeorgLink

**Comment by ritik-malik** [comment]
Hello everyone, I'm Ritik Malik, interested in the above mentioned task. Hoping to have a great interaction with you all :)

**Comment by yash2002109** [comment]
Hello everyone, 

I’m interested to apply for this idea. I have already started working on the microtasks.

Looking forward to contribute.

**Comment by seun-beta** [comment]
Hello @klumb  I created the PR as requested 
https://github.com/chaoss/website/pull/573

**Comment by ritik-malik** [comment]
Hi @klumb @germonprez @GeorgLink,

I've completed the above mentioned microtasks.
Here's the [link to my repository](https://github.com/ritik-malik/Microtasks)

Microtask 1 and Microtask 2 will be updated alongside as I attend the meetings
and make more PRs

Can you please have a look and suggest the required changes?

**Comment by ADI10HERO** [comment]
@klumb 
My doubt is with respect to the third micro task, can we use pre-existing packages to make the converter and kinda make it like a wrapper as per CHAOSS's needs or write one from scratch? (why reinvent the wheel) 
But of course, if something too tailor-made is required, would be more than happy to write one from scratch as well

**Comment by klumb** [comment]
Hi @ADI10HERO, we are open to many different types of proposals. The goal is to come up with an efficient process. If your proposal can do that without reinventing the wheel, that would be great.

**Comment by Molkree** [comment]
I had some automation experience building docs so I would like to share some advice.
As some of you have already noticed, [pandoc](https://pandoc.org/) is probably the best tool for this task, it's what I used too.
Instead of building PDF locally, I suggest creating a [GitHub Actions](https://github.com/features/actions) workflow.
Here is one I used last year: [link to workflow](https://github.com/Molkree/FIIT_6_compiler/blob/master/.github/workflows/DOC_GEN.yml).

---

You won't need `check_doc_changes` job for your task because you will manually run PDF build (use [`workflow_dispatch`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) trigger for that, it allows you to run Actions manually).

In `gen_doc` job you won't need `needs` and `if` fields.

In the first step of a job I checkout the repo, here you will need to [checkout multiple repos](https://github.com/actions/checkout#Checkout-multiple-repos-side-by-side) with metrics MD files (and then move them somewhere convenient maybe). Don't specify `fetch-depth: 0` here like me because it will fetch all history for repos, just last commit is enough for you.

Then I download pandoc package and install it.

A note on dependencies (`sudo apt-get install texlive-xetex texlive-lang-cyrillic librsvg2-bin`): I needed them because docs I built were in Russian, for English you probably won't need anything extra but for translations you most likely will need to install more. It was the main reason why I haven't used `docker://pandoc` image directly, but if you figure out the best image to pull and how to install additional dependencies for languages other than English inside the running container, it might better to use it. Examples are [here](https://github.com/pandoc/pandoc-action-example).

The next step is generating docs! There are two commands in this step because I built combined MD file and combined PDF file, you can skip the first if you want (or you can build PDF from combined MD file, whatever). Notice `$(cat order.txt)` part of the build command, we stored docs order in a separate file because it seemed more convenient than modifying doc order in the pandoc command directly (I believe you will have lots of files).

The next two steps upload resulting files as artifacts to this workflow run, you will probably keep only one for the PDF file.

And finally the last step is for adding the resulting PDF to the repository, it will open a Pull Request with changes you did (here your changes would be adding PDF file).

---

I hope it helps! 😄

**Comment by ADI10HERO** [comment]
@Molkree  Your message is a gem! 
To be honest, I was thinking of some CI workflow for the same, or maybe some CD tool for deployment, but using GitHub-Actions is keeping it simple and getting the job done. Thank you so much for this, it's of immense help.

**Comment by yash2002109** [comment]
The project is now hosted at https://github.com/chaoss/MARS.

The translations process has been added to the [community handbook](https://handbook.chaoss.community/community-handbook/community-initiatives/metrics/translation) and can continue to evolve independently.

Project Final Reports
- @ritik-malik : https://gist.github.com/ritik-malik/5a1a48bb966892824d7da31fc12ede50
- @yash2002109 : https://gist.github.com/yash2002109/887c3e68ff3ff222f941402ceb7bf0dc

Project Trackers
- @ritik-malik : https://github.com/ritik-malik/GSoC
- @yash2002109 : https://github.com/yash2002109/gsoc-21

Shoutout to the @chaoss/metric-release-team, @chaoss/chinese-translators and the entire CHAOSS community for making this project successful.

**Comment by klumb** [comment]
Closing this issue. Nice job everyone!
