### ISSUE TITLE
Google Calender and OutLook Calender Schedule are not matched. 

### ISSUE THREAD

**Issue by eyehwan** [chaoss/website#611]
Hi, 

I download and add outlook ics file from Asia Pacific Call [check your local time](https://arewemeetingyet.com/Chicago/2020-06-17/08:00/b/CHAOSS%20Asia%20Pacific%20Community%20Call), and it is showed one hour later than the schedule showed on Google Calender. 
Meeting on outlook calender starts from 10:00 PM
Meeting on google calender starts from 9:00 PM. 
It makes me miss the last meeting :( , could you help check on it?

Thanks.

**Comment by klumb** [comment]
Thanks @eyehwan 

was the time incorrect in the ics file? Or the check your local time link?

@GeorgLink did you add the “are we meeting” link?

**Comment by germonprez** [comment]
Hi @eyehwan. Could you tell me where you seeing the difference? I'm not seeing a problem.

**Comment by klumb** [comment]
Also, we should probably add China standard time or Beijing time to the calls. We currently have UTC, US central, And central Europe time

**Comment by klumb** [comment]
This is likely a daylight savings time bug in the “are we meeting” application. We may need to remove the link.

**Comment by eyehwan** [comment]
@klumb  and @germonprez, this is what I found: 
![google](https://user-images.githubusercontent.com/1535756/118913156-833e6900-b95b-11eb-928e-9fc5a167f7cd.JPG)
![outlook](https://user-images.githubusercontent.com/1535756/118913162-85082c80-b95b-11eb-8082-2377e1b08562.PNG)

I usually use my outlook calender to schema my meeting, but when I found I missed the meeting yesterday, I checked the schedule on the Google calender, I found this issue. 
The schedule on the Google is correct, when I calculate the time difference by myself. 

As @klumb mentioned, we may need to remove that outlook ics download link, use google calendar as the unique entry point instead.

**Comment by klumb** [comment]
Hi @Eyehwan,

Could you tell me if this is still an issue?

**Comment by eyehwan** [comment]
@klumb
I hope we can remove the wrong link(**add it**) from https://arewemeetingyet.com/Chicago/2020-06-17/08:00/b/CHAOSS%20Asia%20Pacific%20Community%20Call, avoiding any confusions for new people.

**Comment by klumb** [comment]
@eyehwan is the link still giving you the wrong time?

**Comment by klumb** [comment]
does this ICS link work?

https://calendar.google.com/calendar/ical/j9f60skdd67938kvgl0udgqjqs%40group.calendar.google.com/public/basic.ics

**Comment by eyehwan** [comment]
@klumb 

> @eyehwan is the link still giving you the wrong time?

No, it is not working. 

> does this ICS link work?
> 
> https://calendar.google.com/calendar/ical/j9f60skdd67938kvgl0udgqjqs%40group.calendar.google.com/public/basic.ics

This one  is correct.  :)

**Comment by klumb** [comment]
Because this bug is in an external application, we can't really fix it.

So, I propose these changes:

- Let's add China standard time or Beijing time (which one is more appropriate?) to the text in the WG modules - we will have UTC, US Central, Europe Central, and China. 
- Delete the link to the "are we meeting yet" application to avoid confusion
- We could add our own ICS link so individuals can grab the calendar without using Google but I am not sure we want to do this. We have discussed this in the past and decided against it. The problem is that if the calendar changes, users will need to grab a new ICS to update. There is potential here for people to have bad info if they aren't updating the ics on a regular basis. 

@germonprez, @ElizabethN, @GeorgLink - Thoughts?

**Comment by klumb** [comment]
This change will happen after the migration

**Comment by klumb** [comment]
This is resolved
