### ISSUE TITLE
Home Page Update Suggestions

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#695]
Hi everyone, 

I have a few suggestions for the home page (chaoss.community) in an effort to improve simplicity on the page. None of these suggestions immediately impact the navigation at the top. These are all aimed at the text in the document. 

1) Remove CHAOSS Software (we have navigation to it)
2) Remove CHAOSS Initiatives (we have navigation to it) 
3) Remove CHAOSS Working Groups -- perhaps they can be moved to navigation
4) Remove the CHAOSScon banner for now
5) Remove the Twitter feed -- we can just point to our Twitter page 
6) Remove Learn how to Participate and the image from CHAOSScon EU (may add picture back later)
7) Remove CHAOSS Weekly button, they are already available under recent posts
8) With all this space, move the CHAOSS Blog up

That's it for now :)

**Comment by geekygirldawn** [comment]
I like to think of the website as for newcomers and people who don't have any idea what we do, since regular community members are already participating and likely not visiting the website very much. So, what I like about having some of these boxes is that newcomers won't necessarily know why to click on "initiatives" if they don't know something is interesting there, but they might see badging and want to learn more. Similar idea with the working groups and software. 

What if instead, we did something more like this:
* remove the CHAOSScon banner
* Put the blog as the top thing in the left hand column
* Put the Twitter feed under the blog in the left column
* Put everything else in the right hand column - I kind of like keeping the chaosscon picture. But maybe we can get rid of some of the descriptive text above the links for WGs, etc. That might also allow us to make that column a little smaller to give the blog more room?

This would give the blog more visibility while also keeping some of the content visible for newcomers.

Another option would be to move WGs, software and initiatives to a rotating banner, so that people would see them, but not all at once, and maybe we could do something more visual with them? This would also free up space for the blog.

**Comment by klumb** [comment]
I am in favor of these changes. If there is agreement, I can make the edits pretty quickly.

However, it might make sense to keep the high-level description of What CHAOSS is on this page (from the working groups section).

Also, do we want to remove the CHAOSScon banner or just point it somewhere else?

**Comment by klumb** [comment]
The website is not high traffic, we could try these changes out on prod during a set time to help us decide.

**Comment by klumb** [comment]
The primary goal for these edits should be to establish clear pathways for newcomers. In some cases, content can get in the way of that. In others, content is needed. I don't think the existing section with working groups and initiatives creates clear pathways to contribution. So I do think we either need to point them somewhere else or redesign those sections.

**Comment by geekygirldawn** [comment]
Maybe we should take a step back to answer a few questions:
* When a newcomer hits the homepage, what is the first thing we want them to do?
* What do we think are the 2-3 best pathways into participation?
* What can we do to quickly get newcomers productively contributing in a way that encourages them to stay for the longer-term.

**Comment by germonprez** [comment]
Thanks!

I think my main goal was to first reduce the amount of information that was on the page. I think it was overwhelming and that's why I had just a list of 'remove' items :)

In an effort build things back up, yes, it is all about helping newcomers.

1) If I think about our newcomer slack conversations, one of the things that we consistently do is encourage people to attend the Tuesday community call. So maybe this is something to easily highlight on the front page. 
2) Bringing the blog forward is excellent. 

I still lean to not including the entire Twitter feed -- pointing people to Twitter seems okay to me.

**Comment by geekygirldawn** [comment]
I admit that I tend to like having dynamic, up to date things on the home page to draw people into things happening right now, but I agree that maybe it adds too much clutter?

Maybe we cut some things, and remove some of the boxes by replacing them with a specific call to action for newcomers at the top of the page? Something like this, but more visually appealing and with links (these aren't necessarily the right things, but you get the idea):

If you are new to CHAOSS these 4 things will help you get started:
* Join the newcomer Slack channel and introduce yourself.
* Attend the Tuesday community meeting.
* Join the mailing list.
* Visit the participate page to find other ways to get engaged.

**Comment by geekygirldawn** [comment]
This is where I remind people that I have lots of opinions, but I am **terrible** at design and user experience, so I won't be offended if we reduce the clutter to help people focus on more important things :)

**Comment by germonprez** [comment]
I 100% guarantee CHAOSS wouldn't be what it is without your opinions 💯 Keep them coming!! 

I love the four items that you have. I also like the order because the first three are simple to do (one step), they are low overhead, and they can all be done as a listener.

**Comment by klumb** [comment]
I am going to move forward with these suggestions - with the idea that nothing is set in stone and we can tweak this. I will let you know when the changes are live.

**Comment by ElizabethN** [comment]
I'm going to close this issue since the new website design is complete! :tada:
