### ISSUE TITLE
Header overlapping with navigation menu.

### ISSUE THREAD

**Issue by Kamlesh72** [chaoss/website#750]
When I visited Metrics->Metrics Definitions, the header "THE LINUX FOUNDATION PROJECTS" is overlapping with navigation menu. It is working good in all other pages. Except this one - https://chaoss.community/metrics/.
Tested in Safari and Chrome (mac m1).

<img src="https://user-images.githubusercontent.com/90441742/190894620-ebb964dd-0ca1-4e40-b74b-06033e7fc4de.png" width="700" height="450" />

**Comment by yash-yp** [comment]
The issue has occurred previously as well. Reference -> #608

**Comment by dotun2203** [comment]
If you could assign this to me, i'll like to give it a try

**Comment by klumb** [comment]
Yeah, this is a really hard issue to recreate. 

I believe it is a an issue that occurs due to the browser your using and screen size/mobile. Some have the issue and some don't. 

It can't recreate this issue for me on a mac using firefox or chrome.  

The LF header is created in the functions.php folder. Here is the code if you want to try to troubleshoot:

`// Add top LFproj banner/link
add_action('nectar_hook_after_body_open', 'lf_meta_header', 10, 0);
function lf_meta_header() {
  echo '
  	<div id="lf-header">
		<div class="container">
			<a href="https://www.linuxfoundation.org/projects" target="_blank" rel="noopener noreferrer"><img src="' . get_stylesheet_directory_uri() . '/images/logo_lf_projects_horizontal_2018.png"></a>
		</div>
	</div>
';
}`

**Comment by klumb** [comment]
I commented out the code on production. If someone wants to recommend a fix I will implement it. If not, I am okay with removing the banner. It was added by the LF when they were hosting the website.

**Comment by Kamlesh72** [comment]
I want to work on this issue. I am new to development so don't know much about github. Well I forked the repo but can't find the  functions.php folder.

**Comment by klumb** [comment]
@Kamlesh72 sorry about the late reply. I didn't see that you had responded to me right away. We manage a WordPress website so we don't keep our code on GitHub.
