### ISSUE TITLE
Mis-aligned option in Navbar

### ISSUE THREAD

**Issue by meetagrawal09** [chaoss/website#754]
The DEI Event Badging option in the Navbar appears mis-aligned
It gets fine when we scroll down but again mis-aligns on scrolling up

Browser : _**Chrome**_ ( Version 106.0.5249.119 (Official Build) (64-bit) ) and **_Microsoft Edge_** ( Version 106.0.1370.52 )

<img width="960" alt="image" src="https://user-images.githubusercontent.com/73902874/197390781-3cca212a-6e76-4357-a6f8-d6b752925aa7.png">

Can refer the video below - 

https://user-images.githubusercontent.com/73902874/197391117-c64704b6-51fe-4b79-a5d3-f6e647f989c1.mp4

Navbar behaves perfectly well in case of **_Firefox_** browser

**Comment by klumb** [comment]
Thanks for letting us know and for providing the browser information.

This is an issue with dynamic page sizing to accommodate different size monitors and mobile devices. If you make the page a little bit larger or a little bit smaller, the spacing changes.

The spacing issue is especially evident here because of the size of your window and the navigation text being 3 words (long). This will be resolved in the website redesign - we won't have multi-word navigation in the new main nav.
