### ISSUE TITLE
Include Button for "All Metrics" 

### ISSUE THREAD

**Issue by germonprez** [chaoss/website#764]
on the knowledge base, could we include a button or link that is "all metrics" so that someone could get a view of every metric that we have. Same for metrics models.

**Comment by klumb** [comment]
Yes, we can do that.

**Comment by ElizabethN** [comment]
I added tiles for these on the [Metrics KB home page](https://chaoss.community/kbtopic/metrics-and-metrics-models/), and here are the links to each: 

 - [View all metrics](https://chaoss.community/kbtopic/all-metrics/)
 - [View all metrics models](https://chaoss.community/kbtopic/all-metrics-models/)

Note: only 72 metrics are showing up but I think that's perhaps because a few of them turned into models and were unreleased. I'm going to go ahead and close this issue, but feel free to reopen if there's more work to be done here :blush:
