### ISSUE TITLE
KB Working Group About page is empty

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/website#790]
I was looking at the Working Group info on the website, and I noticed that this about page is empty: https://chaoss.community/kb/about-working-groups/

It might be good to have a list of all of our WGs on that page with short descriptions and repo links for each one?

**Comment by klumb** [comment]
I think this page will need to be built in the community repo. However, there is some markdown from the website repo that should give a headstart.

**Comment by ElizabethN** [comment]
We have this info on the main page of the [Community Knowledge Base](https://chaoss.community/kb-chaoss-community/), but I wonder if it gets overlooked, because folks have to scroll to the bottom to see it. We currently don't have an "about-working-groups" page specifically, so that's why it's blank. I'll look into this more and maybe we can move the working group info to that page (or duplicate it since it comes from github anyway). Thanks @geekygirldawn!

**Comment by ElizabethN** [comment]
I'm closing this, as those changes have been made. Happy to re-open this discussion if needed.
