### ISSUE TITLE
Wot in Tarnation [Change Requests Declined Metric]

### ISSUE THREAD

**Issue by GaryPWhite** [chaoss/website#818]
Hello!

I'm perusing the site, like ya do, and noticed [this page looked a little funny](https://chaoss.community/kb/metric-change-requests-declined/). I'd like to make contributions and fix it, but it seems like I'm either unfamiliar with how the site is laid out and can't find the page, or it's not in this repo. I'd be happy to make a contribution to wherever to update it.

![image](https://github.com/chaoss/website/assets/7660110/7ffb862b-ba5e-4df4-a960-5a7c77065774)

**Comment by vinodkahuja** [comment]
@GaryPWhite thank you for pointing this out. Here is the GitHub page where it is pulling from https://github.com/chaoss/wg-evolution/blob/main/focus-areas/code-development-efficiency/change-requests-declined.md

@ElizabethN @klumb On Github, the text display is fine. I guess the issue is from the WP side.

**Comment by klumb** [comment]
Thanks, @GaryPWhite!

The site is managed on WordPress, and we pull content in from GitHub markdown files. We greatly appreciate the offer to help, but unfortunately, this particular problem would require WordPress admin access. 

This issue is likely being caused by our translation software. I checked, and we were running an older version. I have updated our version of the software to the latest release. I believe this should take care of the issue. 

I was unable to recreate the issue on my side. @vinodkahuja were you able to recreate the issue?

@GaryPWhite could you clear your browser cache and confirm that the issue is fixed on your end?

**Comment by vinodkahuja** [comment]
@klumb Thanks! it is fixed now.

**Comment by GaryPWhite** [comment]
lgtm now -- sorry for the delay in respsonse. Thanks!
