### ISSUE TITLE
Licensing docs on the website

### ISSUE THREAD

**Issue by RichardLitt** [chaoss/website#895]
As discussed in the CHAOSS WG today, it would be great to license the practitioner guides, as accessed through the website, with the MIT license. Right now, the footer makes everything appear to be © the Linux Foundation, and there's no mention that the docs are all MIT licensed.

Ideally, this would be a change in the footer, I think. Ping @germonprez @geekygirldawn @ElizabethN

**Comment by geekygirldawn** [comment]
@ElizabethN I wanted to check in on this issue to see if I can help unblock this? It would be amazing if we could get this change made before I talk about the guides at FOSSY :)

**Comment by ElizabethN** [comment]
Hey @geekygirldawn! I put something in slack a while back, but I don't think anyone replied definitively. Is the footer something I can just change? Obviously I'm happy to do it, it's just that IANAL and I don't know if that is ok. I looked at a few other LF projects and the footers all basically say the same thing as ours. It seems like it's a directive of the LF. I don't wanna over-complicate anything. But you know me, I'm a rule follower and I don't want to cause any issues 😅. 

Maybe @klumb knows, since he was involved in the first iteration of the CHAOSS site. @klumb  do you remember if the LF was adamant about the footer on the site? Do you know if we can change it?

**Comment by ElizabethN** [comment]
After several more discussions about this, we have [added a revised footer to the Practitioner Guides](https://github.com/chaoss/wg-data-science/pull/68) clarifying the license under which they have been released. 

I'm going to close this issue, but @RichardLitt if this is something you'd like to continue to discuss or if you feel like there is still some ambiguity, by all means, feel free to reopen this! ✨

**Comment by RichardLitt** [comment]
I trust you. I just wanted to raise it initially - thanks for doing the hard work after I did that!
